package agorasim20.apples.carrots;

import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.FoodComponent;

public class Carrots {
    public static final FoodComponent COAL_CARROT = (new FoodComponent.Builder()).hunger(6).saturationModifier(1.6F).statusEffect(new StatusEffectInstance(StatusEffects.NIGHT_VISION, 300, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HASTE, 100, 0), 1).alwaysEdible().build();
    public static final FoodComponent COPPER_CARROT = (new FoodComponent.Builder()).hunger(6).saturationModifier(1.6F).statusEffect(new StatusEffectInstance(StatusEffects.SPEED, 300, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.WEAKNESS, 100, 0), 1).alwaysEdible().build();
    public static final FoodComponent EMERALD_CARROT = (new FoodComponent.Builder()).hunger(6).saturationModifier(1.6F).statusEffect(new StatusEffectInstance(StatusEffects.HERO_OF_THE_VILLAGE, 100, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 200, 0), 1).alwaysEdible().build();
    public static final FoodComponent LAPIS_CARROT = (new FoodComponent.Builder()).hunger(7).saturationModifier(1.8F).statusEffect(new StatusEffectInstance(StatusEffects.LUCK, 200, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 300, 0), 1).alwaysEdible().build();
    public static final FoodComponent OBSIDIAN_CARROT = (new FoodComponent.Builder()).hunger(6).saturationModifier(1.8F).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 100, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 300, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.WATER_BREATHING, 100, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 100, 0), 1).alwaysEdible().build();
    public static final FoodComponent DIAMOND_CARROT = (new FoodComponent.Builder()).hunger(12).saturationModifier(2F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 400, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 400, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.WATER_BREATHING, 600, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 300, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 600, 1), 1).alwaysEdible().build();
    public static final FoodComponent NETHERITE_CARROT = (new FoodComponent.Builder()).hunger(20).saturationModifier(2F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 600, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 600, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 600, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 800, 2), 1).alwaysEdible().build();
    public static final FoodComponent IRON_CARROT = (new FoodComponent.Builder()).hunger(6).saturationModifier(1.8F).statusEffect(new StatusEffectInstance(StatusEffects.ABSORPTION, 200, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 200, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 400, 0), 1).alwaysEdible().build();
    public static final FoodComponent CREATIVE_CARROT = (new FoodComponent.Builder()).hunger(20).saturationModifier(2F).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 2400, 4), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 4800, 4), 1).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 2400, 4), 1).statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 2400, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.WATER_BREATHING, 2400, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 2400, 2), 1).alwaysEdible().build();
}
